# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6c0de92dfd99d63f166c3d69b94c8831ff7de3c416ddd1d85a1a60f66b8f6b939a31baf44df41213cafb77914a2209bd5f5575693c52b10cee4eebcc5435e3

test:
  secret_key_base: 1e939368ca1fcf34a62bdf23f72bf066aba608f321d2a2178a27b7855baabe8d82e85234163a549d3dd73fe904c72a9626c401745cc2767915a1d067bfb6f1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
